# Generated by Django 5.1.1 on 2024-09-30 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0003_alter_quiz_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='has_time_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
